version: 1

env:
  - CGO_ENABLED=0
  - GO111MODULE=on

flags:
  - -trimpath

ldflags:
  - -s -w
  - -X main.version={{.Tag}}
  - -X main.commit={{.CommitDate}}
  - -X main.builtBy=slsa-github-generator

main: ./cmd/sarc
binary: sarc

goos:
  - linux
  - darwin
  - windows

goarch:
  - amd64
  - arm64

# Exclude windows/arm64 - not a supported release target.
ignore:
  - goos: windows
    goarch: arm64
